# Fundamentals: Python Intro

## Warm Up

In the cell below, import numpy and name it 'np' and create a list with the python data types that you learned about in the pre-lecture. Name the list "types".
Ex.

```
import ... as ...
types = [...]
```

In [4]:
# import numpy and create the list here
import numpy as np

types = [1,2,3,4,5]

In [7]:
# Warmup 1: Call the first element in types and slice the last 2 elements. Print both results.


t1 = types[0]

print (t1)


t2 = types[3:]

print (t2)





1
[4, 5]


In [19]:
# Warmup 2: Divide by 4, the second element in "types". 
#types1 = [1,2/4, 3,4]

#t4 = print(types1)

The code was able to execute because the items of my lists are integers. 

[1, 0.5, 3, 4]


In this text cell, explain why or why not the code was able to execute. (Your explanation does _not_ need to be very detailed.)

## Exercise 1: Creating Data Containers

Create a list, a set, a tuple and an array. 

- The list (in order) should have
  - any 2 numbers as integers
  - any 2 numbers as floating point numbers
  - 2 of your favourite music artists as strings
  - 6 elements total. Name this list **'First'** and print it. 
- The Set (in order) should have
  - 1 even number less than 20
  - 3 of the first letters of the alphabet as strings in seperate entries.
  - 4 elements total. Name this set **'Second'** and print it.
- The Tuple (in order) should have
  - 6 negative numbers.
  - 6 elements total. Name this Tuple **'Third'** and print it.
- The array (in order) should have
  - the same 6 elements as the tuple but these numbers should be positive.
  - 6 elements total. Name this array **'Fourth'** and print it.

In [255]:
# The list
First = [2, 4, 6.5, 8.2,'Gael', 'shilo']
print (First)

[2, 4, 6.5, 8.2, 'Gael', 'shilo']


In [256]:
# The set
Second = {8,'a', 'b', 'c'}

print (Second)

{8, 'a', 'c', 'b'}


In [257]:
# The tuple
Third = (-3, -5, -2 , -9 , -5, -7)

print (Third)

(-3, -5, -2, -9, -5, -7)


In [258]:
# The array

Fourth = np.array ( [3,5,2,9,5,7])

print(Fourth)


[3 5 2 9 5 7]


In [259]:
# Add the second element of 'First', and the last elements of 'Third' and 'Fourth'. Print the result.

element1 = First[1]

element2 = Third [-1]

element3 = Fourth[-1]

e = [element1, element2, element3]


Fourth = np.append(Fourth, e)


print (Fourth)











[ 3  5  2  9  5  7  4 -7  7]


In [260]:
# Slice the last 3 elements of 'Fourth' and append them to the list 'First'. Print the result.



f1 = Fourth [6:9]     # f1 is the 3 elements of Fourth that i am slice

Fourth = Fourth[:-3]  # The new value of Fourth without his 3 last elements

print (f1)

First.extend(f1)      # The new value of first with append the 3 elements

print (Fourth)

print (First)







[ 4 -7  7]
[3 5 2 9 5 7]
[2, 4, 6.5, 8.2, 'Gael', 'shilo', 4, -7, 7]


## Exercise 2: A Dictionary

Create a dictionary with the following keys, 'Name', 'Year', 'Music' and 'Food'. The values associated with each key (in order) should be your name, the current year, you favourite genre of music and one of your favourite foods. Name the dictionary 'Me' and print it. 

In [94]:
# your dictionary here
Me = {'Name': 'Olive', 'Year': '2024', 'Music': 'Shilo', 'Food': 'Rice'}

print (Me)

{'Name': 'Olive', 'Year': '2024', 'Music': 'Shilo', 'Food': 'Rice'}


In [95]:
# Replace the value associated with 'Food' to another one of your favourite foods. Print the updated dictionary.
Me['Food'] = 'Fish'

print (Me)

{'Name': 'Olive', 'Year': '2024', 'Music': 'Shilo', 'Food': 'Fish'}

## Exercise 3: An "original" List

- Create a list with entries 1, 3, 2, 1, 5, 3, 5, 1, 4 and name it 'original'.
- Create another list called 'unique' that only contains unique numbers from original.

Example:

```
Input
[1, 2, 3, 1]

Output
[1, 2, 3]
```
**Hint:** Think about the properties of a set from lecture.


In [2]:
my_list = [1, 2, 3, 4, 1, 5]
my_set = set(my_list)
new_list = list(my_set)  # Correct usage
print(new_list)


[1, 2, 3, 4, 5]


## Exercise 4: Do the Math!

Call the last element of the array "Fourth" that you created above. Raise this element to the second power and add it to the second element of the list "First".

In [261]:
# do the math here...
m1= Fourth[-1]

m2 = m1 **2

First[1] = First[1] + m2

First

[2, 53, 6.5, 8.2, 'Gael', 'shilo', 4, -7, 7]

In [262]:
# Add the last three elements of "Third". 
th =Third [3:]

First.extend(th)

First

[2, 53, 6.5, 8.2, 'Gael', 'shilo', 4, -7, 7, -9, -5, -7]

## Exercise 5: Conversion

- Convert the tuple, "Third" to an array.
- Double all the elements in "Third"
- Add the elements in this array to the elements in "Fourth".

To do this, use only 1 arithmetic statement. Store this result as "Fifth" and print it.

**Hint** Answer should look like this. 

```
Fifth = 2*___(____) + _____
print (Fifth)
```

In [263]:
# conversion here

#Third_Array = np.array(Third)

#Double_Third = Third_Array *2

#t= Double_Third + Fourth

Fifth = 2* np.array(Third) + Fourth

print (Fifth)




[-3 -5 -2 -9 -5 -7]


## Exercise 6: Conditionals

Convert "Fifth" to a tuple and use a print statement to see if Fifth is equal to "Third".

In [1]:
# conditionals here


In [264]:
Fifth = tuple (Fifth)

Fifth

(-3, -5, -2, -9, -5, -7)

In [265]:
if Fifth == Third:
    print ('Fifth is equal to Third')
else:
    print ('Fifth is not equal to Third' )

Fifth is equal to Third
